import type { Metadata } from 'next'
import { Inter, Poppins, Permanent_Marker, Covered_By_Your_Grace } from 'next/font/google'
import './globals.scss'
import NavBar from '@/components/NavBar/NavBar'

const inter = Inter({ subsets: ['latin'] })

const poppins = Poppins(
  {
    weight: '300',
    subsets: ['latin'],
    variable: '--poppins-default'
  }
)

const permanentMarker = Permanent_Marker(
  {
    weight: '400',
    subsets: ['latin'],
    variable: '--permarmentMarker-default'
  }
)

const coveredByYourGrace = Covered_By_Your_Grace(
  {
    weight: '400',
    subsets: ['latin'],
    variable: '--coveredByYourGrace-default'
  }
)

export const metadata: Metadata = {
  title: 'ErickFabian Dev',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${permanentMarker.variable} ${coveredByYourGrace.variable}`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
